name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to EC2
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no -o ConnectTimeout=60 ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP }} "
          git clone git@github.com:jaise007/demo1.git
          sudo mv demo1/index.html /var/www/html
          sudo systemctl restart httpd
          rm -rf demo1
          "
