on:
  push:
    branches:
      - main
    paths:
      - "*/index.html" 
 
jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
 
    steps:
      - name: ssh and do stuff
        run: |
          sudo apt install sshpass -y
          sshpass -p {{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no {{ secrets.SSH_USERNAME }}@{{ secrets.SSH_IP }} "
          git clone git@github.com:jaise007/demo1.git
          mv demo1/index.html /var/www/html
          sudo systemctl restart httpd
          rm -rf demo1
          "
